skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_q3_2026 = "HMqTrRBxW996utybyhDGYcxRvhNtGYqiYzHx56k2zoFA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
